#!/bin/sh
#
# This script is run by pppd after the link is established.
# It should be used to add routes, set IP address, run the mailq, etc.
#
# This script is called with the following arguments:
# Arg  Name               Example
# $1   Interface name     ppp0
# $2   The tty            ttyS1
# $3   The link speed     38400
# $4   Local IP number    12.34.56.78
# $5   Peer  IP number    12.34.56.99
#

# Reset the PATH environment variable
PATH=/usr/sbin:/sbin:/usr/bin:/bin
export PATH

# Get the current date and time
AUTH_TIME="$(date "+%Y-%m-%d_%H:%M:%S")"

# Extract username, interface name, and peer IP address from arguments
USERNAME="${PEERNAME}"
IFACE="${1}"
PEERIP="${5}"

# Stop SQM
if /usr/lib/sqm/run.sh stop "${IFACE}"; then
    # Remove SQM configuration
    uci del sqm."${USERNAME}"
    uci commit sqm

    # Log the execution
    logger "${AUTH_TIME} ${USERNAME} ${IFACE} ${PEERIP} SPEED-LIMIT >>>>>> SQM has been stopped, and its configuration has been removed!"
else
    # Log an error if stopping SQM failed
    logger "${AUTH_TIME} ${USERNAME} ${IFACE} ${PEERIP} SPEED-LIMIT >>>>>> Error: Failed to stop SQM!"
fi

exit 0
