#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2024 OpenWrt.org

START=50
STOP=50
USE_PROCD=1
OPTIONS_FILE=/etc/ppp/pppoe-server-options

pppoe_triggers() {
    local cfg="$1"
    local enabled interface
    config_get_bool enabled "$cfg" enabled 1
    [ "$enabled" -gt 0 ] || return 0
    config_get interface "$cfg" interface
    procd_add_reload_interface_trigger $interface
}

pppoe_instance() {
    local cfg="$1"
    local enabled interface ac_name service_names service_name maxsessionsperpeer localip firstremoteip maxsessions optionsfile randomsession unit offset timeout mss sync OPTIONS
    config_get_bool enabled "$cfg" enabled 1
    [ "$enabled" -gt 0 ] || return 0
    config_get interface "$cfg" interface
    config_get ac_name "$cfg" ac_name
    config_get service_names "$cfg" service_name
    config_get maxsessionsperpeer "$cfg" maxsessionsperpeer
    config_get localip "$cfg" localip
    config_get firstremoteip "$cfg" firstremoteip
    config_get maxsessions "$cfg" maxsessions
    config_get optionsfile "$cfg" optionsfile
    config_get_bool randomsession "$cfg" randomsession 1
    config_get_bool unit "$cfg" unit 0
    config_get offset "$cfg" offset
    config_get timeout "$cfg" timeout
    config_get mss "$cfg" mss
    config_get_bool sync "$cfg" sync 0
    config_get_bool use_non_uci_config "$cfg" use_non_uci_config 0

    if [ "$use_non_uci_config" -gt 0 ]; then
        . /etc/default/pppoe-server || logger -t "pppoe-server" "Failed to load configuration"
    else
        [ -n "$ac_name" ] && append OPTIONS "-C $ac_name"
        for service_name in $service_names; do
            append OPTIONS "-S $service_name"
        done
        append OPTIONS "-I $interface"
        [ -n "$maxsessionsperpeer" ] && append OPTIONS "-x $maxsessionsperpeer"
        [ -n "$localip" ] && append OPTIONS "-L $localip"
        [ -n "$firstremoteip" ] && append OPTIONS "-R $firstremoteip"
        [ -n "$maxsessions" ] && append OPTIONS "-N $maxsessions"
        [ -n "$optionsfile" ] && append OPTIONS "-O $optionsfile"
        [ "$randomsession" = "1" ] && append OPTIONS "-r"
        [ "$unit" = "1" ] && append OPTIONS "-u"
        [ -n "$offset" ] && append OPTIONS "-o $offset"
        [ -n "$timeout" ] && append OPTIONS "-T $timeout"
        [ -n "$mss" ] && append OPTIONS "-m $mss"
        [ "$sync" = "1" ] && append OPTIONS "-s"
    fi

    procd_open_instance
    procd_set_param command /usr/sbin/pppoe-server -F -k $OPTIONS
    procd_set_param respawn
    procd_set_param file /etc/ppp/options
    procd_append_param file /etc/ppp/pppoe-server-options
    procd_close_instance
}

pppoe_pppd() {
    local cfg="$1"
    local pap chap mschapv2 authmode ipv6 lcp_echo_interval lcp_echo_failure mtu mru msdns1 msdns2 logfile debug more mswins1 mswins2
    config_get pap "$cfg" pap
    config_get chap "$cfg" chap
    config_get mschapv2 "$cfg" mschapv2
    config_get authmode "$cfg" authmode
    config_get ipv6 "$cfg" ipv6
    config_get lcp_echo_interval "$cfg" lcp_echo_interval
    config_get lcp_echo_failure "$cfg" lcp_echo_failure
    config_get mtu "$cfg" mtu
    config_get mru "$cfg" mru
    config_get msdns1 "$cfg" msdns1
    config_get msdns2 "$cfg" msdns2
    config_get logfile "$cfg" logfile
    config_get debug "$cfg" debug
    config_get more "$cfg" more
    config_get mswins1 "$cfg" mswins1
    config_get mswins2 "$cfg" mswins2

    cat <<-EOF > ${OPTIONS_FILE}
	# PPP options for the PPPoE server
	# LIC: GPL
	${pap}
	${chap}
	${mschapv2}
	${authmode}
	${ipv6}
	lcp-echo-interval ${lcp_echo_interval}
	lcp-echo-failure ${lcp_echo_failure}
	mtu ${mtu}
	mru ${mru}
	ms-dns ${msdns1}
	ms-dns ${msdns2}
	logfile ${logfile}
	${debug}
EOF
}

pppoe_firewall() {
    local cfg="$1"
    local isolation conntrackmax
    config_get isolation "$cfg" isolation
    config_get conntrackmax "$cfg" conntrackmax

    if [ -n "$conntrackmax" ]; then
        sed -i '/net.netfilter.nf_conntrack_max/d' /etc/sysctl.d/11-nf-conntrack.conf
        echo "net.netfilter.nf_conntrack_max=${conntrackmax}" >> /etc/sysctl.d/11-nf-conntrack.conf
        /etc/init.d/sysctl restart || logger -t "pppoe-server" "Failed to restart sysctl"
    fi
}

start_service() {
    config_load pppoe-server
    config_foreach pppoe_instance server
    config_foreach pppoe_pppd pppd
    config_foreach pppoe_firewall firewall
}

service_triggers() {
    procd_add_reload_trigger "pppoe-server"

    config_load pppoe-server
    config_foreach pppoe_triggers server
    config_foreach pppoe_triggers pppd
    config_foreach pppoe_triggers firewall
}
