#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pppoeuser[-1]
	add ucitrack pppoeuser
	set ucitrack.@pppoeuser[-1].init=pppoeuser
	commit ucitrack
EOF

chmod 600 /etc/config/pppoeuser
chmod 755 /etc/init.d/pppoeuser
chmod 755 /etc/ppp/ip-up /etc/ppp/ip-down
chmod 755 /etc/ppp/auth-up /etc/ppp/auth-down
#iptables -w -t mangle -N pppoe_user
#iptables -w -t mangle -I FORWARD -j pppoe_user

rm -rf /tmp/luci-*cache
exit 0
