#
# Copyright (C) 2008-2023 The LuCI Team <luci@lists.subsignal.org>
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=QoS over Nftables
LUCI_DESCRIPTION:=Provides Luci for Nft-Qos Unofficial
LUCI_DEPENDS:=+luci-compat +nft-qos
LUCI_PKGARCH:=all

PKG_DATE:=2023-01-10

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
