#!/bin/sh

export initscript="pppoe-qos-dynamic"

. /lib/functions.sh

PPPOE_TIME="$(date "+%Y-%m-%d_%H:%M:%S")"
echo "$PPPOE_TIME Track INTERFACE=$INTERFACE, DEVICE=$DEVICE, MACADDR=$MACADDR, IPADDR=$IPADDR, HOSTNAME=$HOSTNAME ACTION=$ACTION" >> /var/log/interface.log

case "$ACTION" in
	add | update | remove)
		qosdef_validate_dynamic default qosdef_check_if_dynamic
		[ -z "$NFT_QOS_DYNAMIC_ON" ] && return

		qosdef_init_env
		qosdef_flush_dynamic

		qosdef_init_header
		qosdef_validate_dynamic default qosdef_init_dynamic
		qosdef_init_done
		qosdef_start
		;;
esac
