#!/bin/sh

export initscript="pppoe-iface-dynamic"

. /lib/functions.sh

PPPOE_TIME="$(date "+%Y-%m-%d_%H:%M:%S")"
echo "$PPPOE_TIME Track Interface=$INTERFACE, Device=$DEVICE, MACaddr=$MACADDR, IPaddr=$IPADDR, Hostname=$HOSTNAME Action=$ACTION" >> /var/log/interface.log
