#!/bin/sh /etc/rc.common

START=99

CHAP_SECRETS=/etc/ppp/chap-secrets
chmod 600 /etc/ppp/*-secrets

setup_user() {
	local cfg="$1"
	config_get enabled $1 enabled
	[ "$enabled" -eq 0 ] && return 0
	config_get username $1 username
	config_get servicename $1 servicename
	[ -n "${servicename}" ] || servicename="*"
	config_get password $1 password
	config_get ipaddress $1 ipaddress
	[ -n "$username" -a -n "$password" ] && echo "$username $servicename $password $ipaddress" >> $CHAP_SECRETS
	config_get sqm $1 sqm
	config_get download $1 download
	config_get upload $1 upload
	config_get qdisc $1 qdisc
	config_get script $1 script
	config_get linklayer $1 linklayer

	uci del sqm.eth1 >/dev/null 2>&1
        uci set sqm.$username=queue >/dev/null 2>&1
        uci set sqm.$username.enabled=$sqm >/dev/null 2>&1
        uci set sqm.$username.download=$download >/dev/null 2>&1
        uci set sqm.$username.upload=$upload >/dev/null 2>&1
        uci set sqm.$username.qdisc=$qdisc >/dev/null 2>&1
        uci set sqm.$username.script=$script >/dev/null 2>&1
        uci set sqm.$username.linklayer=$linklayer >/dev/null 2>&1
        uci set sqm.$username.debug_logging=0 >/dev/null 2>&1
        uci set sqm.$username.verbosity=5 >/dev/null 2>&1
        uci set sqm.$username.overhead=0 >/dev/null 2>&1
        uci commit sqm
}

delete_user() {
	rm -rf $CHAP_SECRETS
}

start() {
	config_load pppoe-client
	delete_user
	config_foreach setup_user user
}

stop() {
	delete_user
	killall -q pppoe-client
}
