#!/bin/sh /etc/rc.common

START=99

CONFIG="*"
CHAP_SECRETS=/var/etc/chap-secrets
TEMP=/tmp/$CONFIG.tmp

setup_user() {
	local cfg="$1"
	config_get enabled $1 enabled
	[ "$enabled" -eq 0 ] && return 0
	config_get username $1 username
	config_get servicename $1 servicename
	[ -n "${servicename}" ] || servicename="*"
	config_get password $1 password
	config_get ipaddress $1 ipaddress
	[ -n "$username" -a -n "$password" ] && echo "$username $servicename $password $ipaddress" >> $CHAP_SECRETS
	config_get sqm $1 sqm
	config_get download $1 download
	config_get upload $1 upload
	config_get qdisc $1 qdisc
	config_get script $1 script
	config_get linklayer $1 linklayer

	del sqm.eth1
	set sqm.$username=queue
	set sqm.$username.enabled=$sqm
	set sqm.$username.download=$download
	set sqm.$username.upload=$upload
	set sqm.$username.qdisc=$qdisc
	set sqm.$username.debug_logging=0
	set sqm.$username.verbosity=5
	set sqm.$username.script=$script
	set sqm.$username.qdisc_advanced=0
	set sqm.$username.linklayer=$linklayer
	set sqm.$username.overhead=0
}

del_user()
{
	cat $CHAP_SECRETS | grep -v $CONFIG > $TEMP
	cat $TEMP > $CHAP_SECRETS
	rm $TEMP
}

start() {
	config_load pppoe-client
	del_user
	config_foreach setup_user user
	ln -sfn $CHAP_SECRETS /etc/ppp/chap-secrets
	chmod 600 /etc/ppp/chap-secrets
	chmod 600 /etc/ppp/pap-secrets
	chmod 600 /var/etc/chap-secrets
}

stop() {
	del_user
	killall -q pppoe-client
}
