#!/bin/sh /etc/rc.common

START=99

CONFIG="*"
CHAP_SECRETS=/etc/ppp/chap-secrets
TEMP=/tmp/$CONFIG.tmp

setup_user() {
	local cfg="$1"
	config_get enabled $1 enabled
	[ "$enabled" -eq 0 ] && return 0
	config_get username $1 username
	config_get servicename $1 servicename
	[ -n "${servicename}" ] || servicename="*"
	config_get password $1 password
	config_get ipaddress $1 ipaddress
	[ -n "$username" -a -n "$password" ] && echo "$username $servicename $password $ipaddress" >> $CHAP_SECRETS
}

del_user()
{
	cat $CHAP_SECRETS | grep -v $CONFIG > $TEMP
	cat $TEMP > $CHAP_SECRETS
	rm $TEMP
}

start() {
	config_load pppoe-client
	del_user
	config_foreach setup_user user
}

stop() {
	del_user
	killall -q pppoe-client
}
