#!/bin/sh
#
# A program or script which is executed after the remote system
# successfully authenticates itself. It is executed with the parameters
# <interface-name> <peer-name> <user-name> <tty-device> <speed>
#

#
# The environment is cleared before executing this script
# so the path must be reset
#
PATH=/usr/sbin:/sbin:/usr/bin:/bin
export PATH

AUTH_TIME="$(date "+%Y-%m-%d_%H:%M:%S")"

/usr/lib/sqm/run.sh stop "$1"
uci del sqm."$2"
uci commit sqm

SQM_STOPPING=$(tc -s qdisc show dev "$1")

echo "$AUTH_TIME $2 Stopping QOS: $SQM_STOPPING" >> /home/log/userdown.log

exit 0
