#!/bin/sh
#
# A program or script which is executed after the remote system
# successfully authenticates itself. It is executed with the parameters
# <interface-name> <peer-name> <user-name> <tty-device> <speed>
#

#
# The environment is cleared before executing this script
# so the path must be reset
#
PATH=/usr/sbin:/sbin:/usr/bin:/bin
export PATH

IFACE="$1"
USERNAME="$2"

SQM_STOPPING=$(tc -s qdisc show dev "$IFACE")
AUTH_TIME="$(date "+%Y-%m-%d_%H:%M:%S")"

/usr/lib/sqm/run.sh stop "$IFACE"
uci del sqm."$USERNAME"
uci commit sqm

echo "$AUTH_TIME $USERNAME $IFACE Stopping QOS $SQM_STOPPING" >> /var/log/userqos.log

exit 0
