#!/bin/sh
#
# A program or script which is executed after the remote system
# successfully authenticates itself. It is executed with the parameters
# <interface-name> <peer-name> <user-name> <tty-device> <speed>
#

#
# The environment is cleared before executing this script
# so the path must be reset
#
PATH=/usr/sbin:/sbin:/usr/bin:/bin
export PATH

IFACE="$1"
USERNAME="$2"

AUTH_TIME="$(date "+%Y-%m-%d_%H:%M:%S")"
USER_CONFIG="pppoe-user"
USER_CFGID="$(uci show $USER_CONFIG | grep "$USERNAME" | cut -d '.' -sf 2)"
USER_QOS="$(uci get $USER_CONFIG."$USER_CFGID".qos)"
USER_DOWNLOAD="$(uci get $USER_CONFIG."$USER_CFGID".download)"
USER_UPLOAD="$(uci get $USER_CONFIG."$USER_CFGID".upload)"

QOS_STARTING="$(tc -s qdisc show dev "$IFACE" | grep qdisc)"
echo "$AUTH_TIME $USERNAME $IFACE Starting QOS $QOS_STARTING" >> /var/log/userqos.log

exit 0
