#!/bin/sh

DOWNTIME="$(date "+%Y-%m-%d %H:%M:%S")"
CONFIG="pppoe-user"
CONFIG_PATH=/var/etc/${CONFIG}
SESSION_PATH=${CONFIG_PATH}/session

USERNAME=${PEERNAME}
IFACE=${1}
TTY=${2}
SPEED=${3}
LOCALIP=${4}
PEERIP=${5}
REMOTEIP=${6}

rm -f ${SESSION_PATH}/${USERNAME}.${IFACE}

/usr/lib/sqm/run.sh stop $IFNAME
uci del sqm.$PEERNAME.interface
uci commit sqm

rm -f /var/run/$IFNAME.pid

echo $PEERNAME $IFNAME $5 $DOWNTIME Offline >> /var/log/offlineusername.log
