#!/bin/sh
#
# This script is run by the pppd _after_ the link is brought down.
# It should be used to delete routes, unset IP addresses etc.
#
# This script is called with the following arguments:
#    Arg  Name               Example
#    $1   Interface name     ppp0
#    $2   The tty            ttyS1
#    $3   The link speed     38400
#    $4   Local IP number    12.34.56.78
#    $5   Peer  IP number    12.34.56.99
#

#
# The  environment is cleared before executing this script
# so the path must be reset
#
PATH=/usr/sbin:/sbin:/usr/bin:/bin
export PATH

PPPOE_TIME="$(date "+%Y-%m-%d_%H:%M:%S")"
PPPOE_LOG="/var/log/pppoeuser"
PPPOE_LOG_FILE="${PPPOE_LOG}/$PEERNAME.log"
SESSION_PATH="/var/etc/pppoe-user/session"

rm -f ${SESSION_PATH}/${PEERNAME}.${IFNAME}

echo "$PPPOE_TIME $PEERNAME Offline $IFNAME $DEVICE $IPREMOTE Connection times: $CONNECT_TIME Send Bytes: $BYTES_SENT Received Bytes: $BYTES_RCVD" >> /var/log/userdown.log

echo "$PPPOE_TIME $PEERNAME Offline interface: $IFNAME device: $DEVICE clientIP: $IPREMOTE" >> $PPPOE_LOG_FILE
echo "Connect time: $CONNECT_TIME minutes" >> $PPPOE_LOG_FILE
echo "Sent: $BYTES_SENT bytes" >> $PPPOE_LOG_FILE
echo "Received: $BYTES_RCVD bytes" >> $PPPOE_LOG_FILE
sum_bytes=$(($BYTES_SENT+$BYTES_RCVD))
sum=`echo "scale=2;$sum_bytes/1024/1024"|bc`
echo "Bytes sum: $sum MB" >> $PPPOE_LOG_FILE
ave=`echo "scale=2;$sum_bytes/1024/$CONNECT_TIME"|bc`
echo "Average speed: $ave KB/s" >> $PPPOE_LOG_FILE
echo >> $PPPOE_LOG_FILE

uci del sqm.$PEERNAME
uci commit sqm
#/usr/lib/sqm/run.sh stop $IFNAME
rm -f /var/run/sqm/$IFNAME.state
rm -f /var/run/sqm/$IFNAME.iptables.log

echo "$PPPOE_TIME $PEERNAME Stopping SQM on $IFNAME" >> /var/log/userdown.log

exit 0
