#!/bin/sh
#
# This script is run by the pppd after the link is established.
# It should be used to add routes, set IP address, run the mailq
# etc.
#
# This script is called with the following arguments:
#    Arg  Name               Example
#    $1   Interface name     ppp0
#    $2   The tty            ttyS1
#    $3   The link speed     38400
#    $4   Local IP number    12.34.56.78
#    $5   Peer  IP number    12.34.56.99
#

#
# The  environment is cleared before executing this script
# so the path must be reset
#
PATH=/usr/sbin:/sbin:/usr/bin:/bin
export PATH

PPPOE_TIME="$(date "+%Y-%m-%d_%H:%M:%S")"
PPPOE_LOG="/var/log/pppoeuser"
PPPOE_LOG_FILE="${PPPOE_LOG}/$PEERNAME.log"
CONFIG="pppoe-user"
CONFIG_PATH="/var/etc/${CONFIG}"
SESSION_PATH="${CONFIG_PATH}/session"
CFGID="$(uci show $CONFIG | grep $PEERNAME | cut -d '.' -sf 2)"
USER_PACKAGE="$(uci get $CONFIG.$CFGID.package)"
USER_QOS="$(uci get $CONFIG.$CFGID.qos)"
USER_DOWNLOAD="$(uci get $CONFIG.$CFGID.download)"
USER_UPLOAD="$(uci get $CONFIG.$CFGID.upload)"
USER_CONNECT="$(uci get $CONFIG.$CFGID.connect)"
RENEWAL_DATE="$(uci get $CONFIG.$CFGID.expires)"

#SQM_ENABLED="$(uci get $CONFIG.$CFGID.qos)"
#SQM_INTERFACE="$IFNAME"
#SQM_DOWNLOAD="$(uci get $CONFIG.$CFGID.upload)"
#SQM_UPLOAD="$(uci get $CONFIG.$CFGID.download)"
#SQM_QDISC="$(uci get $CONFIG.$CFGID.qdisc)"
#SQM_SCRIPT="$(uci get $CONFIG.$CFGID.script)"
#SQM_LINKLAYER="$(uci get $CONFIG.$CFGID.linklayer)"
#SQM_DEBUG_LOGGING="0"
#SQM_VERBOSITY="5"
#SQM_OVERHEAD="44"

USERNAME=${PEERNAME}
IFACE=${1}
TTY=${2}
SPEED=${3}
LOCALIP=${4}
PEERIP=${5}
REMOTEIP=${6}

PID="$(cat /var/run/${IFNAME}.pid 2>/dev/null)"
MAC="$(top -bn1 | grep pppoe-server | grep "${PID}" | grep -E -o "[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){6}" | cut -d : -f 2,2-7)"

mkdir -p ${PPPOE_LOG}
mkdir -p ${SESSION_PATH}

echo "$PPPOE_TIME Online $PEERNAME $IFNAME $PID $DEVICE $IPREMOTE $MAC" >> /var/log/pppoelog.log

echo "$PPPOE_TIME Online $PEERNAME interface: $IFNAME pid: $PID device: $DEVICE clientIP: $IPREMOTE clientMAC: $MAC" >> $PPPOE_LOG_FILE
echo >> $PPPOE_LOG_FILE

cat <<-EOF > ${SESSION_PATH}/${USERNAME}.${IFACE}
	{
	    "username": "${USERNAME}",
	    "mac": "${MAC}",
	    "pid": "${PID}",
	    "interface": "${IFACE}",
	    "tty": "${TTY}",
	    "speed": "${SPEED}",
	    "ip": "${PEERIP}",
	    "package": "${USER_PACKAGE}",
	    "uptime": "${PPPOE_TIME}",
	    "updated": "${RENEWAL_DATE}"
	}
EOF

cfgid=$(uci show ${CONFIG} | grep "@user" | grep "\.username='${USERNAME}'" | cut -d '.' -sf 2)
[ -n "$cfgid" ] && {
	HAS_LOGIN=$(ls ${SESSION_PATH} | grep "^${USERNAME}\.ppp" | grep -v "${IFACE}")
	[ -n "$HAS_LOGIN" ] && {
		KO_IFACE=$(echo $HAS_LOGIN | awk -F '.' '{print $2}')
		KO_PID=$(cat /var/run/${KO_IFACE}.pid 2>/dev/null)
		[ -n "$KO_PID" ] && kill -15 ${KO_PID} >/dev/null 2>&1
		rm -f ${SESSION_PATH}/${HAS_LOGIN}
		rm -f /var/run/${KO_IFACE}.pid
	}
}

#uci del sqm.eth1
#uci set sqm.$PEERNAME=queue
#uci set sqm.$PEERNAME.enabled=$SQM_ENABLED
#uci set sqm.$PEERNAME.interface=$IFNAME
#uci set sqm.$PEERNAME.download=$SQM_DOWNLOAD
#uci set sqm.$PEERNAME.upload=$SQM_UPLOAD
#uci set sqm.$PEERNAME.qdisc=$SQM_QDISC
#uci set sqm.$PEERNAME.script=$SQM_SCRIPT
#uci set sqm.$PEERNAME.linklayer=$SQM_LINKLAYER
#uci set sqm.$PEERNAME.debug_logging=$SQM_DEBUG_LOGGING
#uci set sqm.$PEERNAME.verbosity=$SQM_VERBOSITY
#uci set sqm.$PEERNAME.overhead=$SQM_OVERHEAD
#uci commit sqm
#/usr/lib/sqm/run.sh start $IFNAME

exit 0
