#!/bin/sh
#
# This script is run by the pppd after the link is established.
# It should be used to add routes, set IP address, run the mailq
# etc.
#
# This script is called with the following arguments:
#    Arg  Name               Example
#    $1   Interface name     ppp0
#    $2   The tty            ttyS1
#    $3   The link speed     38400
#    $4   Local IP number    12.34.56.78
#    $5   Peer  IP number    12.34.56.99
#

#
# The  environment is cleared before executing this script
# so the path must be reset
#
PATH=/usr/sbin:/sbin:/usr/bin:/bin
export PATH

UPTIME="$(date "+%Y-%m-%d %H:%M:%S")"
CONFIG="pppoe-user"
CONFIG_PATH=/var/etc/${CONFIG}
SESSION_PATH=${CONFIG_PATH}/session

USERNAME=${PEERNAME}
IFACE=${1}
TTY=${2}
SPEED=${3}
LOCALIP=${4}
PEERIP=${5}
REMOTEIP=${6}

PID="$(cat /var/run/${IFACE}.pid 2>/dev/null)"
MAC=$(top -bn1 | grep pppoe-server | grep "${PID}" | grep -E -o "[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){6}" | cut -d : -f 2,2-7)

echo >> /var/log/onlineusername.log
echo username: $PEERNAME interface: $IFNAME device: $DEVICE clientIP: $IPREMOTE time: `date -d today +%F_%T` Online >> /var/log/onlineusername.log

mkdir -p ${SESSION_PATH}

cat <<-EOF > ${SESSION_PATH}/${USERNAME}.${IFACE}
	{
	    "username": "${USERNAME}",
	    "interface": "${IFACE}",
	    "tty": "${TTY}",
	    "speed": "${SPEED}",
	    "ip": "${PEERIP}",
	    "mac": "${MAC}",
	    "pid": "${PID}",
	    "uptime": "${UPTIME}",
	    "downtime": "${DOWNTIME}",
	    "renewaldate": "${RENEWALDATE}"
	}
EOF

cfgid=$(uci show ${CONFIG} | grep "@user" | grep "\.username='${USERNAME}'" | cut -d '.' -sf 2)
[ -n "$cfgid" ] && {
	HAS_LOGIN=$(ls ${SESSION_PATH} | grep "^${USERNAME}\.ppp" | grep -v "${IFACE}")
	[ -n "$HAS_LOGIN" ] && {
		KO_IFACE=$(echo $HAS_LOGIN | awk -F '.' '{print $2}')
		KO_PID=$(cat /var/run/${KO_IFACE}.pid 2>/dev/null)
		[ -n "$KO_PID" ] && kill -9 ${KO_PID} >/dev/null 2>&1
		rm -f ${SESSION_PATH}/${HAS_LOGIN}
		rm -f /var/run/${KO_IFACE}.pid
	}
}

uci set sqm.$PEERNAME.interface=$IFNAME
uci commit sqm

/usr/lib/sqm/run.sh start $IFNAME

exit 0
