#!/bin/sh /etc/rc.common

START=60
STOP=60

CHAP_SECRETS=/etc/ppp/chap-secrets

setup_user() {
	local cfg="$1"
	config_get enabled "$1" enabled
	[ "$enabled" -eq 0 ] && return 0
	config_get username "$1" username
	config_get servicename "$1" servicename
	[ -n "${servicename}" ] || servicename="*"
	config_get password "$1" password
	config_get ipaddress "$1" ipaddress
	config_get package "$1" package
	config_get qos "$1" qos
	config_get upload "$1" upload
	config_get download "$1" download
	config_get unit "$1" unit
	config_get connect "$1" connect

	touch ${CHAP_SECRETS}
	[ -n "$username" -a -n "$password" ] && echo "$username $servicename $password $ipaddress" >> $CHAP_SECRETS
        chmod 600 /etc/ppp/*-secrets
}

delete_user() {
	rm -rf $CHAP_SECRETS
}

start() {
	config_load pppoe-user
	delete_user
	config_foreach setup_user user
}

stop() {
	delete_user
	killall -q pppoe-user
}
