#!/bin/sh /etc/rc.common

START=99

CHAP_SECRETS=/etc/ppp/chap-secrets

setup_user() {
	local cfg="$1"
	config_get enabled $1 enabled
	[ "$enabled" -eq 0 ] && return 0
	config_get username $1 username
	config_get servicename $1 servicename
	[ -n "${servicename}" ] || servicename="*"
	config_get password $1 password
	config_get ipaddress $1 ipaddress
	config_get macaddress $1 macaddress
	[ -n "$username" -a -n "$password" ] && echo "$username $servicename $password $ipaddress" >> $CHAP_SECRETS
	config_get qos $1 qos
	[ -n "${qos}" ] || qos="1"
	config_get download $1 download
	config_get upload $1 upload

	nft add table bridge pppoe-qos-mac
	nft add chain bridge pppoe-qos-mac upload { type filter hook prerouting priority 0\; }
	nft add chain bridge pppoe-qos-mac download { type filter hook postrouting priority 0\; }
	nft insert rule bridge pppoe-qos-mac upload iifname br-lan accept
	nft insert rule bridge pppoe-qos-mac download iifname br-lan accept
	nft insert rule bridge pppoe-qos-mac upload ether saddr $macaddress limit rate over $upload kbytes/second counter drop
	nft insert rule bridge pppoe-qos-mac download ether daddr $macaddress limit rate over $download kbytes/second counter drop

        chmod 600 /etc/ppp/*-secrets
}

delete_user() {
	rm -rf $CHAP_SECRETS
	nft delete table bridge pppoe-qos-mac 2>/dev/null
}

start() {
	config_load pppoe-user
	delete_user
	config_foreach setup_user user
}

stop() {
	delete_user
	killall -q pppoe-user
}
