#!/bin/sh /etc/rc.common

START=40
STOP=40

CHAP_SECRETS=/etc/ppp/chap-secrets

setup_user() {
	local cfg="$1"
	config_get enabled "$1" enabled
	[ "$enabled" -eq 0 ] && return 0
	config_get username "$1" username
	config_get servicename "$1" servicename
	[ -n "${servicename}" ] || servicename="*"
	config_get password "$1" password
	config_get ipaddr "$1" ipaddr
	config_get macaddr "$1" macaddr
	config_get package "$1" package
	config_get qos "$1" qos
	config_get urate "$1" urate
	config_get drate "$1" drate
	config_get unit "$1" unit
	[ -n "${unit}" ] || unit="kbytes"
	config_get connect "$1" connect

	touch ${CHAP_SECRETS}
	[ -n "$username" -a -n "$password" ] && echo "$username $servicename $password $ipaddr" >> $CHAP_SECRETS
        chmod 600 /etc/ppp/*-secrets
}

delete_user() {
	cp -rf $CHAP_SECRETS /etc/ppp/user-chap-secrets
	rm -rf $CHAP_SECRETS
}

start() {
	config_load pppoeuser
	delete_user
	config_foreach setup_user user
}

stop() {
	delete_user
	killall -q pppoeuser
}
