#!/bin/sh /etc/rc.common

START=90
STOP=90

CURRENT_DATE=$(date +"%Y-%m-%d")
CHAP_SECRETS=/etc/ppp/chap-secrets
BACKUP_FILE=/home/backup
mkdir -p "${BACKUP_FILE}"

setup_user() {
    local cfg="$1"
    config_get enabled "$cfg" enabled
    config_get username "$cfg" username
    config_get servicename "$cfg" servicename
    [ -n "$servicename" ] || servicename="*"
    config_get password "$cfg" password
    config_get ipaddr "$cfg" ipaddr
    config_get expires "$cfg" expires

    if [ "$expires" == "$CURRENT_DATE" ]; then
        uci set pppoeuser."$cfg".enabled=0
        uci commit pppoeuser
    fi

    # Do not append to the CHAP_SECRETS file if the user is not enabled
    if [ "$enabled" -eq 1 ] && [ "$expires" != "$CURRENT_DATE" ]; then
        echo "$username $servicename $password $ipaddr" >> "$CHAP_SECRETS"
    fi
}

daily_check() {
    (crontab -u root -l ; echo "30 8 * * * /etc/init.d/pppoeuser start") | sort - | uniq - | crontab -u root -
    (crontab -u root -l ; echo "59 8 * * * cp -f /etc/config/pppoeuser /home/backup/\$(date +\%Y\%m\%d%H%M)-pppoeuser.bak") | sort - | uniq - | crontab -u root -
    (crontab -u root -l ; echo "59 20 * * * cp -f /etc/config/pppoeuser /home/backup/\$(date +\%Y\%m\%d%H%M)-pppoeuser.bak") | sort - | uniq - | crontab -u root -
}

start() {
    cp -rf "$CHAP_SECRETS" /etc/ppp/lasttime-chap-secrets
    > "$CHAP_SECRETS"
    daily_check
    config_load pppoeuser
    config_foreach setup_user user
    chmod 600 "$CHAP_SECRETS"
}

stop() {
    killall -q pppoeuser
}
