#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pppoe-client[-1]
	add ucitrack pppoe-client
	set ucitrack.@pppoe-client[-1].init=pppoe-client
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
