#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pppoe-client[-1]
	add ucitrack pppoe-client
	set ucitrack.@pppoe-client[-1].init=pppoe-client
	commit ucitrack
EOF

chmod 0600 /etc/ppp/chap-secrets /etc/ppp/pap-secrets

rm -f /tmp/luci-indexcache
exit 0
