#!/bin/sh

chmod 0600 /etc/config/pppoe-client
chmod 0755 /etc/init.d/pppoe-client
chmod 0755 /etc/ppp/ip-up /etc/ppp/ip-down

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pppoe-client[-1]
	add ucitrack pppoe-client
	set ucitrack.@pppoe-client[-1].init=pppoe-client
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
