# Copyright (C) 2020-2022 Hyy2001X <https://github.com/Hyy2001X>

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for iPerf3
LUCI_DEPENDS:=+luci-compat +iperf3
LUCI_PKGARCH:=all
PKG_VERSION:=2.0
PKG_RELEASE:=3
PKG_DATE:=2022-06-19

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
