#!/bin/sh

chmod 0600 /etc/config/pppoe-user
chmod 0755 /etc/init.d/pppoe-user
chmod 0755 /etc/ppp/ip-up /etc/ppp/ip-down

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pppoe-user[-1]
	add ucitrack pppoe-user
	set ucitrack.@pppoe-user[-1].init=pppoe-user
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
