#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pppoe-user[-1]
	add ucitrack pppoe-user
	set ucitrack.@pppoe-user[-1].init=pppoe-user
	commit ucitrack
EOF

chmod 600 /etc/config/pppoe-user
chmod 755 /etc/init.d/pppoe-user
chmod 755 /etc/ppp/auth-up /etc/ppp/ip-down
chmod 755 /etc/ppp/auth-up /etc/ppp/ip-down
iptables -w -t mangle -N pppoe_user 2>/dev/null
iptables -w -t mangle -C FORWARD -j pppoe_user >/dev/null 2>&1 || iptables -w -t mangle -I FORWARD -j pppoe_user

rm -rf /tmp/luci-*cache
exit 0
