#!/bin/sh

CONFIG="pppoe-client"
CONFIG_PATH=/var/etc/${CONFIG}
SESSION_PATH=${CONFIG_PATH}/session
LOGOUT_TIME="$(TZ=CST-8 date "+%Y-%m-%d %H:%M:%S")"

USERNAME=${PEERNAME}
IFACE=${1}
TTY=${2}
SPEED=${3}
LOCALIP=${4}
PEERIP=${5}
REMOTEIP=${6}

rm -f ${SESSION_PATH}/${USERNAME}.${IFACE}
rm -f /var/run/${IFACE}.pid

Sent=`echo "scale=2;$BYTES_SENT/1024/1024"|bc`
Received=`echo "scale=2;$BYTES_RCVD/1024/1024"|bc`
Connect=$CONNECT_TIME
sum_bytes=$(($BYTES_SENT+$BYTES_RCVD))
sum=`echo "scale=2;$sum_bytes/1024/1024"|bc`
ave=`echo "scale=2;$sum_bytes/1024/$CONNECT_TIME"|bc`

uci del sqm.$PEERNAME.interface
uci commit sqm
/usr/lib/sqm/run.sh stop $IFACE

echo $USERNAME $LOGOUT_TIME Offline Sent: $Sent MB, Received: $Received MB, Connect: $Connect, Sum bytes: $sum MB, Average speed: $ave KB/s >> /var/log/pppoe-client.log
