#!/bin/sh

CONFIG="pppoe-client"
CONFIG_PATH=/var/etc/${CONFIG}
SESSION_PATH=${CONFIG_PATH}/session
LOGOUT_TIME="$(TZ=CST-8 date "+%Y-%m-%d %H:%M:%S")"

USERNAME=${PEERNAME}
IFACE=${1}
TTY=${2}
SPEED=${3}
LOCALIP=${4}
PEERIP=${5}
REMOTEIP=${6}
BYTES_SENT=${BYTES_SENT}
BYTES_RCVD=${BYTES_RCVD}
CONNECT_TIME=${CONNECT_TIME}

rm -f ${SESSION_PATH}/${USERNAME}.${IFACE}
rm -f /var/run/${IFACE}.pid

uci del sqm.$PEERNAME.interface
uci commit sqm

echo $USERNAME $LOGOUT_TIME Offline [ Connect time $CONNECT_TIME, Sent $BYTES_SENT bytes, Received $BYTES_RCVD bytes. ]  >> /var/log/pppoe-client.log
