#!/bin/sh

DOWNTIME="$(date "+%Y-%m-%d %H:%M:%S")"
CONFIG="pppoe-client"
CONFIG_PATH=/var/etc/${CONFIG}
SESSION_PATH=${CONFIG_PATH}/session

USERNAME=${PEERNAME}
IFACE=${1}
TTY=${2}
SPEED=${3}
LOCALIP=${4}
PEERIP=${5}
REMOTEIP=${6}

Sent=`echo "scale=2;$BYTES_SENT/1024/1024"|bc`
Received=`echo "scale=2;$BYTES_RCVD/1024/1024"|bc`
Connect=$CONNECT_TIME
sum_bytes=$(($BYTES_SENT+$BYTES_RCVD))
sum=`echo "scale=2;$sum_bytes/1024/1024"|bc`
ave=`echo "scale=2;$sum_bytes/1024/$CONNECT_TIME"|bc`

uci del sqm.$PEERNAME.interface
uci commit sqm
/usr/lib/sqm/run.sh stop $IFACE

rm -f ${SESSION_PATH}/${USERNAME}.${IFACE}
rm -f /var/run/${IFACE}.pid

echo $USERNAME $DOWNTIME Offline Sent: $Sent MB, Received: $Received MB, Connect: $Connect, Sum bytes: $sum MB, Average speed: $ave KB/s >> /var/log/pppoe-client.log

SCRIPT="/usr/share/${CONFIG}/ip-down.d/${USERNAME}"
[ -s "$SCRIPT" ] && {
	[ ! -x "$SCRIPT" ] && chmod 0755 "$SCRIPT"
	"$SCRIPT" "$@"
}
