#!/bin/sh

CONFIG="pppoe-client"
CONFIG_PATH=/var/etc/${CONFIG}
SESSION_PATH=${CONFIG_PATH}/session
LOGIN_TIME="$(date "+%Y-%m-%d %H:%M:%S")"
USERCONUT="$(uci show ${CONFIG} | grep "@user" | grep "${PEERNAME}" | cut -d '.' -sf 2)"
RENEWAL_DATE="$(uci show ${CONFIG}."${USERCONUT}".expires | grep "expires" | cut -d '=' -sf 2 | cut -d "'" -sf 2)"

USERNAME=${PEERNAME}
IFACE=${1}
TTY=${2}
SPEED=${3}
LOCALIP=${4}
PEERIP=${5}
REMOTEIP=${6}

PID="$(cat /var/run/${IFACE}.pid 2>/dev/null)"
MAC=$(top -bn1 | grep pppoe-server | grep "${PID}" | grep -E -o "[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){6}" | cut -d : -f 2,2-7)

mkdir -p ${SESSION_PATH}

cat <<-EOF > ${SESSION_PATH}/${USERNAME}.${IFACE}
	{
	    "username": "${USERNAME}",
	    "interface": "${IFACE}",
	    "tty": "${TTY}",
	    "speed": "${SPEED}",
	    "ip": "${PEERIP}",
	    "mac": "${MAC}",
	    "pid": "${PID}",
	    "login_time": "${LOGIN_TIME}",
	    "renewal_date": "${RENEWAL_DATE}"
	}
EOF

uci set sqm.$PEERNAME.interface=$IFACE
uci commit sqm
/usr/lib/sqm/run.sh start $IFACE

echo $USERNAME $MAC $IFACE $PEERIP Online $LOGIN_TIME >> /var/log/pppoe-client.log
