#!/bin/sh

CONFIG="pppoe-client"
CONFIG_PATH=/var/etc/${CONFIG}
SESSION_PATH=${CONFIG_PATH}/session
LOGIN_TIME="$(TZ=CST-8 date "+%Y-%m-%d %H:%M:%S")"

USERNAME=${PEERNAME}
IFACE=${1}
TTY=${2}
SPEED=${3}
LOCALIP=${4}
PEERIP=${5}
REMOTEIP=${6}

PID="$(cat /var/run/${IFACE}.pid 2>/dev/null)"
MAC=$(top -bn1 | grep -v grep | grep pppoe-server | grep "${PID}" | grep -E -o "[0-9A-Fa-f]{2}(:[0-9A-Fa-f]{2}){6}" | cut -d : -f 2,2-7)

mkdir -p ${SESSION_PATH}

cat <<-EOF > ${SESSION_PATH}/${USERNAME}.${IFACE}
	{
	    "username": "${USERNAME}",
	    "interface": "${IFACE}",
	    "tty": "${TTY}",
	    "speed": "${SPEED}",
	    "ip": "${PEERIP}",
	    "mac": "${MAC}",
	    "pid": "${PID}",
	    "renewal_date": "${RENEWAL_DATE}",
	    "login_time": "${LOGIN_TIME}"
	}
EOF

uci set sqm.$PEERNAME.interface=$IFACE
uci commit sqm
/usr/lib/sqm/run.sh start

echo $USERNAME $LOGIN_TIME Online $MAC $PEERIP >> /var/log/pppoe-client.log
